#ifndef __TEST_ERRORS_H__
#define __TEST_ERRORS_H__

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

enum {
    NSFTL_SUCCESS = 0U,
    NSFTL_TEST_INDEX_BIGGER_THAN_CATEGORY_SIZE = 1U,
    NSFTL_MEMORY_ALLOCATION_FAILED_MEMORY_INSUFFICIENT = 2U,
    NSFTL_UNABLE_TO_SUBMIT_TEST_FUNCTION_TO_TEST_UNIT = 3U,
    NSFTL_REPORT_MESSAGE_IS_TOO_LONG = 4U,
    NSFTL_TEST_CATEGORY_NOT_INITIALIZED = 5U,
    NSFTL_TEST_CATEGORY_REPORT_ARRAY_NOT_INITIALIZED = 6U,
    NSFTL_TEST_REPORT_NOT_INITIALIZED = 7U,
    NSFTL_TEST_UNIT_NOT_INITIALIZED = 8U,
    NSFTL_TEST_REPORT_START_TIME_NOT_INITIALIZED = 9U,
    NSFTL_TEST_REPORT_END_TIME_NOT_INITIALIZED = 10U,
    NSFTL_TEST_REPORT_FAILED_TO_GET_CLOCK_TIME = 11U,
    NSFTL_CLOCK_TIME_NOT_INITIALIZED = 12U,
    NSFTL_UNABLE_TO_RETRIEVE_CLOCK_TIME = 13U
};

#ifdef __cplusplus
}
#endif

#endif