#ifndef __TEST_ERRORS_H__
#define __TEST_ERRORS_H__

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

enum {
    MYTEST_SUCCESS = 0U,
    MYTEST_TEST_INDEX_BIGGER_THAN_CATEGORY_SIZE = 1U,
    MYTEST_MEMORY_ALLOCATION_FAILED_MEMORY_INSUFFICIENT = 2U,
    MYTEST_UNABLE_TO_SUBMIT_TEST_FUNCTION_TO_TEST_UNIT = 3U,
    MYTEST_REPORT_MESSAGE_IS_TOO_LONG = 4U,
    MYTEST_TEST_CATEGORY_NOT_INITIALIZED = 5U,
    MYTEST_TEST_CATEGORY_REPORT_ARRAY_NOT_INITIALIZED = 6U
};

#ifdef __cplusplus
}
#endif

#endif